package com.deathmotion.keybindfetcher.util;

import java.util.Set;

public class VanillaKeybindsUtil {
    public static final Set<String> VANILLA_KEYBINDS = Set.of(
            "key.advancements",
            "key.attack",
            "key.back",
            "key.chat",
            "key.command",
            "key.debug.clearChat",
            "key.debug.copyLocation",
            "key.debug.copyRecreateCommand",
            "key.debug.crash",
            "key.debug.debugOptions",
            "key.debug.dumpDynamicTextures",
            "key.debug.dumpVersion",
            "key.debug.focusPause",
            "key.debug.fpsCharts",
            "key.debug.modifier",
            "key.debug.networkCharts",
            "key.debug.overlay",
            "key.debug.profiling",
            "key.debug.profilingChart",
            "key.debug.reloadChunk",
            "key.debug.reloadResourcePacks",
            "key.debug.showAdvancedTooltips",
            "key.debug.showChunkBorders",
            "key.debug.showHitboxes",
            "key.debug.spectate",
            "key.debug.switchGameMode",
            "key.drop",
            "key.forward",
            "key.fullscreen",
            "key.hotbar.1",
            "key.hotbar.2",
            "key.hotbar.3",
            "key.hotbar.4",
            "key.hotbar.5",
            "key.hotbar.6",
            "key.hotbar.7",
            "key.hotbar.8",
            "key.hotbar.9",
            "key.inventory",
            "key.jump",
            "key.left",
            "key.loadToolbarActivator",
            "key.pickItem",
            "key.playerlist",
            "key.quickActions",
            "key.right",
            "key.saveToolbarActivator",
            "key.screenshot",
            "key.smoothCamera",
            "key.sneak",
            "key.socialInteractions",
            "key.spectatorHotbar",
            "key.spectatorOutlines",
            "key.sprint",
            "key.swapOffhand",
            "key.toggleGui",
            "key.togglePerspective",
            "key.toggleSpectatorShaderEffects",
            "key.use"
    );

}
